import{a as v,S,i}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function r(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=r(o);fetch(o.href,n)}})();const f=async(e,t)=>{try{const r=new URLSearchParams({q:e,key:"53365400-7139be9e5523c93bff54612dc",image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15});return(await v.get(`https://pixabay.com/api/?${r}`)).data}catch(r){console.log("Помилка",r)}};let u=null;function m(){u?u.refresh():u=new S(".gallery a")}const p=e=>`<li class="gallery-card">
  <a class="img-link" href="${e.largeImageURL}">           <img class="img" src="${e.webformatURL}" alt="${e.tags}"title="${e.tags}"/></a>
  <div class="gallery-info">
  <p class="info-item">Likes <span>${e.likes}</span></p>
  <p class="info-item">Views <span>${e.views}</span></p>          
  <p class="info-item">Comments <span>${e.comments}</span></p>
  <p class="info-item">Downloads <span>${e.downloads}</span></p>
  </div>
  </li>`;function B(e,t){const r=e.map(s=>p(s)).join("");t.innerHTML=r,m()}function P(e,t){const r=e.map(p).join("");t.insertAdjacentHTML("beforeend",r),m()}function q(e){e.innerHTML=""}function g(e){e.classList.remove("hidden")}function h(e){e.classList.add("hidden")}function y(e){e.classList.remove("hidden")}function L(e){e.classList.add("hidden")}const a={searchForm:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadmoreBtn:document.querySelector(".loadmore-btn")},b=15;let l=1,c=null,w=null;const C=async e=>{try{e.preventDefault();const{target:t}=e;if(c=t.elements["search-text"].value.trim(),c===""){i.error({message:"Please fill in the search field"});return}q(a.gallery),g(a.loader),L(a.loadmoreBtn),l=1;const r=await f(c,l),s=r.hits;if(s.length===0){i.info({message:"Sorry, no images found. Try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"red"});return}const o=Math.ceil(r.totalHits/b);B(s,a.gallery),w=a.gallery.querySelector("li").getBoundingClientRect().height,o>1&&y(a.loadmoreBtn),t.elements["search-text"].value=""}catch{i.error({message:"Something went wrong",position:"topRight",backgroundColor:"red"})}finally{h(a.loader)}},R=async e=>{try{l++,L(a.loadmoreBtn),g(a.loader);const t=await f(c,l),r=t.hits;if(r.length>0){P(r,a.gallery),scrollBy({top:w*2,behavior:"smooth"});const s=Math.ceil(t.totalHits/b);l<s?y(a.loadmoreBtn):i.info({message:"We are sorry, but you have reached the end of search results.",position:"topRight",backgroundColor:"green"})}}catch(t){console.log(t)}finally{h(a.loader)}};a.searchForm.addEventListener("submit",C);a.loadmoreBtn.addEventListener("click",R);
//# sourceMappingURL=index.js.map
