import{a as v,S as w,i}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function a(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(o){if(o.ep)return;o.ep=!0;const n=a(o);fetch(o.href,n)}})();const m=async(e,t)=>{try{const a=new URLSearchParams({q:e,key:"53365400-7139be9e5523c93bff54612dc",image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15});return(await v.get(`https://pixabay.com/api/?${a}`)).data}catch(a){console.log("Помилка",a)}},f=new w(".gallery a"),p=e=>`<li class="gallery-card">
  <a class="img-link" href="${e.largeImageURL}">           <img class="img" src="${e.webformatURL}" alt="${e.tags}"title="${e.tags}"/></a>
  <div class="gallery-info">
  <p class="info-item">Likes <span>${e.likes}</span></p>
  <p class="info-item">Views <span>${e.views}</span></p>          
  <p class="info-item">Comments <span>${e.comments}</span></p>
  <p class="info-item">Downloads <span>${e.downloads}</span></p>
  </div>
  </li>`;function B(e,t){const a=e.map(s=>p(s)).join("");t.innerHTML=a,f.refresh()}function S(e,t){const a=e.map(p).join("");t.insertAdjacentHTML("beforeend",a),f.refresh()}function P(e){e.innerHTML=""}function g(e){e.classList.remove("hidden")}function h(e){e.classList.add("hidden")}function u(e){e.classList.remove("hidden")}function y(e){e.classList.add("hidden")}const r={searchForm:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadmoreBtn:document.querySelector(".loadmore-btn")};let l=1,c=null,L=null;const q=async e=>{try{e.preventDefault();const{target:t}=e;if(c=t.elements["search-text"].value.trim(),c===""){i.error({message:"Please fill in the search field"});return}P(r.gallery),g(r.loader),y(r.loadmoreBtn),l=1;const a=await m(c,l),s=a.hits;if(s.length===0){i.info({message:"Sorry, no images found. Try again!",position:"topRight",messageColor:"#fafafb",backgroundColor:"red"});return}Math.ceil(a.totalHits/15)>1&&(u(r.loadmoreBtn),r.loadmoreBtn.addEventListener("click",b)),B(s,r.gallery),L=r.gallery.querySelector("li").getBoundingClientRect().height,u(r.loadmoreBtn),t.elements["search-text"].value=""}catch(t){i.error({message:"Something went wrong",position:"topRight",backgroundColor:"red"}),console.log(t)}finally{h(r.loader)}},b=async e=>{try{l++,g(r.loader);const t=await m(c,l),a=t.hits;S(a,r.gallery),scrollBy({top:L*2,behavior:"smooth"});const s=Math.ceil(t.totalHits/15);l>=s&&(y(r.loadmoreBtn),r.loadmoreBtn.removeEventListener("click",b),i.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight",backgroundColor:"green"}))}catch(t){console.log(t)}finally{h(r.loader)}};r.searchForm.addEventListener("submit",q);
//# sourceMappingURL=index.js.map
